// Content data for BDecors 3D — Riyadh, Saudi Arabia
// Equipment: 2× Bambu Lab H2D AMS Combo with AMS HT
window.SITE_DATA = {
  brand: "BDecors 3D",
  phone: "+966 56 840 0053",
  email: "3d@bdecors.com",
  address: {
    line1: "King Fahd Road",
    line2: "Olaya District, Riyadh",
    country: "Kingdom of Saudi Arabia",
    mapUrl: "https://share.google/WF4cLDMaVjPvSCXI0",
  },
  marquee: [
    "INTERIOR DESIGN",
    "FURNITURE ACCESSORIES",
    "AUTOMOTIVE PARTS",
    "INDUSTRIAL PARTS",
    "AI 2D → 3D",
    "RIYADH · KSA",
    "ACTION FIGURES",
    "CUSTOM NAME LAMPS",
    "POKÉMON · DINOS · HEROES",
    "GIFTS · LOGOS · SIGNAGE",
    "MULTI-COLOR PRINTS",
    "SAME-DAY DELIVERY",
  ],
  stats: [
    { num: "500+", label: "Parts Printed" },
    { num: "16", label: "Colors Per Print" },
    { num: "Same-day", label: "Riyadh Delivery" },
    { num: "AI", label: "2D → 3D Studio" },
  ],
  simpleServices: [
    {
      icon: "rocket",
      title: "Rapid Prototyping",
      desc: "Turn your concepts into reality within hours. Perfect for product development and testing.",
    },
    {
      icon: "cube",
      title: "Custom Parts Manufacturing",
      desc: "Precision 3D printed parts for industrial, automotive, and consumer applications.",
    },
    {
      icon: "spark",
      title: "AI-Powered 2D to 3D",
      desc: "Upload a photo and we'll convert it to a printable 3D model using SUAPP AI technology.",
    },
  ],
  printCategories: [
    { icon: "phone", name: "Custom Phone Cases", tag: "Consumer" },
    { icon: "wrench", name: "Mechanical Parts", tag: "Industrial" },
    { icon: "building", name: "Architectural Models", tag: "Architecture" },
    { icon: "cube", name: "Product Prototypes", tag: "Design" },
    { icon: "heart", name: "Medical Models", tag: "Healthcare" },
    { icon: "user", name: "Custom Figurines", tag: "Entertainment" },
    { icon: "diamond", name: "Jewelry & Accessories", tag: "Fashion" },
    { icon: "car", name: "Automotive Parts", tag: "Automotive" },
    { icon: "rocket", name: "Drone Components", tag: "Aerospace" },
    { icon: "book", name: "Educational Models", tag: "Education" },
    { icon: "lamp", name: "Home Decor", tag: "Interior" },
    { icon: "tool", name: "Replacement Parts", tag: "Repair" },
    { icon: "mask", name: "Cosplay Props", tag: "Entertainment" },
    { icon: "box", name: "Custom Enclosures", tag: "Electronics" },
    { icon: "sign", name: "Signage & Displays", tag: "Marketing" },
    { icon: "trophy", name: "Sports Equipment", tag: "Sports" },
    { icon: "paw", name: "Pet Accessories", tag: "Pets" },
    { icon: "utensil", name: "Kitchen Tools", tag: "Home" },
  ],
  services: [
    {
      num: "01",
      icon: "lamp",
      title: "Interior Design Pieces",
      desc: "Sculptural vases, planters, lampshades, wall panels, and decor accents printed to your space and palette.",
      tone: "warm",
      images: [
        { type: "photo", src: "images/doves-installed.jpg" },
        { type: "photo", src: "images/doves-interior.jpg" },
        { type: "photo", src: "images/hands-planter.jpg" },
      ],
    },
    {
      num: "02",
      icon: "building",
      title: "Furniture Accessories",
      desc: "Custom handles, knobs, brackets, hinges, table legs, and hard-to-find replacement parts.",
      tone: "warm",
      images: [
        { type: "art", shape: "cabinet-handle" },
        { type: "art", shape: "drawer-knob" },
        { type: "art", shape: "bracket" },
      ],
    },
    {
      num: "03",
      icon: "car",
      title: "Automotive Parts",
      desc: "Interior trim, custom mounts, dashboard clips, and out-of-stock replacement parts — measured and matched.",
      tone: "cool",
      images: [
        { type: "art", shape: "vent-clip" },
        { type: "art", shape: "dash-mount" },
        { type: "art", shape: "badge" },
      ],
    },
    {
      num: "04",
      icon: "wrench",
      title: "Industrial & Engineering",
      desc: "Functional brackets, jigs, fixtures, manifolds, and architectural maquettes in carbon-filled composites.",
      tone: "cool",
      images: [
        { type: "art", shape: "l-bracket" },
        { type: "art", shape: "maquette" },
        { type: "art", shape: "jig" },
      ],
    },
    {
      num: "05",
      icon: "lamp",
      title: "Custom Lamps & Figures",
      desc: "Named lamps in Arabic & English, Pokémon and superhero glow lamps, dinosaur night lights, busts, and collectible figures.",
      tone: "warm",
      images: [
        { type: "photo", src: "images/astronaut-figure.jpg" },
        { type: "art", shape: "name-lamp-aisha" },
        { type: "art", shape: "pokemon-lamp-pika" },
      ],
    },
    {
      num: "06",
      icon: "spark",
      title: "Gifts · Logos · Signage",
      desc: "Bespoke gifts, corporate logos, plaques, name signs, awards — anything that should feel made for someone.",
      tone: "sand",
      images: [
        { type: "photo", src: "images/silk-road-logo.jpg" },
        { type: "art", shape: "plaque" },
        { type: "art", shape: "trophy" },
      ],
    },
  ],
  // Bambu Lab H2D-compatible filaments only. No resins, no SLS powders.
  materials: [
    { name: "PLA Basic", tag: "Decor / Figures", color: "#00b4ff", strength: 70, heat: 35, flex: 30 },
    { name: "PLA Silk", tag: "Premium Finish", color: "#c08bff", strength: 65, heat: 35, flex: 30 },
    { name: "PETG HF", tag: "Furniture / Functional", color: "#2D9B7C", strength: 78, heat: 65, flex: 55 },
    { name: "ABS", tag: "Mechanical / Impact", color: "#1F3A5F", strength: 85, heat: 85, flex: 60 },
    { name: "ASA", tag: "Outdoor / UV Stable", color: "#e6e2d8", strength: 82, heat: 90, flex: 55 },
    { name: "PC (Polycarbonate)", tag: "High-Strength", color: "#0c0d10", strength: 92, heat: 110, flex: 50 },
    { name: "TPU 95A", tag: "Flexible / Soft-touch", color: "#7B3F8F", strength: 50, heat: 65, flex: 95 },
    { name: "PA-CF (Nylon-CF)", tag: "Industrial Grade", color: "#222428", strength: 96, heat: 95, flex: 70 },
  ],
  steps: [
    { n: "01", title: "Upload", desc: "Drop your STL, STEP, 3MF — or a sketch and let our AI generate the model." },
    { n: "02", title: "Configure", desc: "Pick material, color, layer height, and finish. We auto-quote in real time." },
    { n: "03", title: "Print", desc: "Your job enters our print queue. Live progress updates as it prints, finishes, and is QC-checked." },
    { n: "04", title: "Deliver", desc: "QC check, careful packaging, and same-day Riyadh delivery or KSA-wide shipping." },
  ],
  industries: [
    { icon: "lamp", title: "Interior Design", desc: "Decor pieces, planters, lampshades, and wall art tailored to your space." },
    { icon: "building", title: "Furniture & Joinery", desc: "Replacement parts, custom hardware, and accent components for cabinetmakers." },
    { icon: "wrench", title: "Industrial & Workshops", desc: "Brackets, jigs, fixtures, manifolds, and tooling in carbon-filled plastics." },
    { icon: "cube", title: "Architecture & Studios", desc: "Massing models, presentation maquettes, and scale prototypes." },
    { icon: "rocket", title: "Collectors & Hobbyists", desc: "Action figures, dioramas, tabletop minis, and licensed-style busts." },
    { icon: "spark", title: "Corporate Gifting", desc: "Branded gifts, awards, logos, and signage with multi-color detail." },
  ],
  gallery: [
    { name: "Astronaut Display", category: "Figures", img: "images/astronaut-figure.jpg" },
    { name: "Hands Planter", category: "Interior", img: "images/hands-planter.jpg" },
    { name: "Flying Doves Wall Art", category: "Interior", img: "images/doves-installed.jpg" },
    { name: "Hands Planter (Detail)", category: "Interior", img: "images/hands-planter-2.jpg" },
    { name: "Doves — Staircase Install", category: "Interior", img: "images/doves-interior.jpg" },
    { name: "Silk Road Co. — Logo Sign", category: "Gifts", img: "images/silk-road-logo.jpg" },
    { name: "Aisha — Named Lamp", category: "Lamps", shape: "name-lamp", arabicName: "عائشة", romanName: "Aisha" },
    { name: "Layla — Named Lamp", category: "Lamps", shape: "name-lamp", arabicName: "ليلى", romanName: "Layla" },
    { name: "Pikachu Glow Lamp", category: "Lamps", shape: "pokemon-lamp" },
    { name: "Dino Night Light", category: "Lamps", shape: "dino-lamp" },
    { name: "Knight Bust", category: "Figures", shape: "bust" },
    { name: "Geometric Vase", category: "Interior", shape: "vase" },
  ],
  faqs: [
    { q: "What kinds of things do you print?", a: "Interior decor (vases, planters, lampshades, wall panels), furniture accessories (handles, brackets, hardware), automotive parts (trim clips, mounts, replacements), industrial parts (jigs, fixtures, brackets, maquettes), action figures and collectibles, plus gifts, logos, and signage." },
    { q: "What materials do you offer?", a: "PLA Basic, PLA Silk, PETG HF, ABS, ASA, PC (Polycarbonate), TPU 95A, and PA-CF (carbon-fiber-reinforced nylon). Each comes in a wide color range — see the materials page for properties." },
    { q: "Can you do multi-color prints?", a: "Yes — we can run up to 16 colors or materials in a single print without manual swaps, and we offer color-matching from Pantone, RAL, and brand guidelines." },
    { q: "How fast is your turnaround?", a: "Most small pieces (figures, accessories, small decor) ship same-day or next-day from Riyadh. Larger furniture and architectural pieces are quoted on a per-project basis with delivery dates confirmed up front." },
    { q: "What file formats do you accept?", a: "STL, STEP, 3MF, and OBJ natively. We can also work from Solidworks, Fusion 360, Rhino, and Blender source files. No file? Sketch or photo via the AI Studio." },
    { q: "Do you ship outside Riyadh?", a: "Yes — we ship across the Kingdom of Saudi Arabia and the wider GCC. Same-day couriers in Riyadh, next-day to Jeddah, Dammam, and Khobar." },
    { q: "Do you do post-processing?", a: "Sanding, priming, painting, and color-matching. We also install threaded inserts, magnets, and LED housings on request." },
  ],
};
